baseURL: "https://auroraldiffraction.github.io/"
languageCode: en-us
title: Auroral Diffraction
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: AuroralDiffraction.github.io
  description: "Auroral Diffraction's Website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "AuroralDiffraction"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true
    title: "Auroral Diffraction" # optional default will be site title
    subtitle: "Analog Circuit Design"
    imageUrl: "/images/profile/profilePic.jpg" # optional
    # imageUrl: "/images/profile/drone.png" # optional
    imageTitle: "Profile image" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: About Me
        url: "/post/about/"
      - name: Blogs
        url: "/blogs"
      # - name: Archives
      #   url: "/archives"
      - name: Github
        url: "https://github.com/AuroralDiffraction"
      

  

  # home-info mode
  homeInfoParams:
    Title: "Hi there, I'm Auroral Diffraction \U0001F44B"
    Content: Welcome to my blog
    buttons:
      - name: About Me
        url: "/post/about/"
      - name: Blogs
        url: "/blogs"
      # - name: Archives
      #   url: "/archives"
      - name: Github
        url: "https://github.com/AuroralDiffraction"
      
    

  socialIcons:
    - name: twitter
      url: "https://twitter.com/Tanatonium"
    # - name: linkedin
    #   url: "https://www.linkedin.com/in/zhiyuanyao-ee/"
    - name: github
      url: "https://github.com/AuroralDiffraction"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /post/about/
      weight: 1
    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 10
    - identifier: posts
      name: Posts
      url: /post/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai